apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: dask-demo
spec:
  serviceAccountName: client-account
  containers:
    - name: dask
      image: ghcr.io/dask/dask:2024.5.2-py3.11
      command: [ "/bin/sh", "-c", "sleep infinity" ]